# -*- coding: utf-8 -*-
"""Hello World with fpdf2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/py-pdf/fpdf2/blob/master/tutorial/notebook.ipynb

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/py-pdf/fpdf2/blob/master/tutorial/notebook.ipynb) <hr> [![Open In nbviewer](https://img.shields.io/badge/Open_In-nbviewer-blue?logo=jupyter)](https://nbviewer.org/github/py-pdf/fpdf2/blob/master/tutorial/notebook.ipynb)

# Hello World with fpdf2
This [Jupyter notebook](https://jupyter.org/) demontrates some basic usage of the Python [fpdf2](https://github.com/py-pdf/fpdf2) library
"""

# Installation of fpdf2 with PIP:
!pip install fpdf2

# Enable deprecation warnings:
import warnings
warnings.simplefilter('default', DeprecationWarning)

# Generate a PDF:
from fpdf import FPDF
pdf = FPDF()
pdf.add_page()
pdf.set_font('helvetica', size=48)
pdf.cell(text="hello world")
pdf_bytes = pdf.output()

# Display the PDF in the notebook by embedding it as HTML content:
WIDTH, HEIGHT = 800, 400
from base64 import b64encode
from IPython.display import display, HTML
base64_pdf = b64encode(pdf_bytes).decode("utf-8")
display(HTML(f'<embed src="data:application/pdf;base64,{base64_pdf}" width="{WIDTH}" height="{HEIGHT}" type="application/pdf">'))

# Display a download button:
display(HTML(f'<a download="fpdf2-demo.pdf" href="data:application/pdf;base64,{base64_pdf}">Click to download PDF</a>'))

"""To continue learning about `fpdf2`, check our tutorial:
- [English](https://py-pdf.github.io/fpdf2/Tutorial.html)
- [Deutsch](https://py-pdf.github.io/fpdf2/Tutorial-de.html)
- [español](https://py-pdf.github.io/fpdf2/Tutorial-es.html)
- [हिंदी](https://py-pdf.github.io/fpdf2/Tutorial-हिंदी.html)
- [português](https://py-pdf.github.io/fpdf2/Tutorial-pt.html)
- [Русский](https://py-pdf.github.io/fpdf2/Tutorial-ru.html)
- [Italian](https://py-pdf.github.io/fpdf2/Tutorial-it.html)
- [français](https://py-pdf.github.io/fpdf2/Tutorial-fr.html)
- [Ελληνικά](https://py-pdf.github.io/fpdf2/Tutorial-gr.html)
- [עברית](https://py-pdf.github.io/fpdf2/Tutorial-he.html)
- [Dutch](https://py-pdf.github.io/fpdf2/Tutorial-nl.html)
- [Polski](https://py-pdf.github.io/fpdf2/Tutorial-pl.html)
- [Türkçe](https://py-pdf.github.io/fpdf2/Tutorial-tr.html)
- [Indonesian](https://py-pdf.github.io/fpdf2/Tutorial-id.html)
"""
